### PR TITLE
Business independent

### PR DESCRIPTION
**Pull request by laugimethods**

### CODE REVIEW

**Comment by laugimethods** [comment]
No more need for a experimental branch.

**Comment by laugimethods** [comment]
Sorry, I was supposed to merge with my local master branch, not the killrweather one.

**Comment by helena** [comment]
@laugimethods Hi, sorry I haven't replied to your PRs yet, will next week :)

**Comment by laugimethods** [comment]
There is no hurry.

As already said, you could create a dedicated branch where I can push my code, so to keep the current code as the reference until my update is fixed & validated.

**Pull request closed without merging**
