### PR TITLE
Moved Spark Streaming into a separate module

### PR DESCRIPTION
**Pull request by retroryan**
Moved Spark Streaming into a separate module so that it could be run as a stand-alone spark job.  This enables it to be run outside the Akka Actor context.  This is critical for allow the application to run with DataStax Analytics.

### CODE REVIEW

**Comment by retroryan** [comment]
I am not entirely sure the original design intention.  It seems that:

- killrweather-app starts an Actor System running the PrecipitationActor, TemperatureActor, etc.  
- killrweather-app starts in cluster mode so clients can send messages to the Actor's by joining in the same akka cluster

The problem was the akka client seed nodes (killrweather-clients) where not defined by default so they they didn't join the (killrweather-app) cluster.  

- A default seed node was add to make this easy to run.
- In killrweather-clients reference.conf set the seed nodes to be localhost
- For remote deployment this will be need to be set to the host of killrweather-app

**Comment by retroryan** [comment]
There is still one error outstanding on the client, which is likely a version mismatch:

Driver stacktrace:
org.apache.spark.SparkException: Job aborted due to stage failure: Task 7 in stage 35.0 failed 1 times, most recent failure: Lost task 7.0 in stage 35.0 (TID 91, localhost): java.lang.ClassCastException: com.datastax.driver.core.DefaultResultSetFuture cannot be cast to shade.com.datastax.spark.connector.google.common.util.concurrent.ListenableFuture

**Comment by pmcfadin** [comment]
Time to take it for a test spin... Thanks again Ryan!

**Comment by pmcfadin** [comment]
@retroryan I just did a clean build and found a big problem in KafkaStreamingActorSpec.

Line 47 has a reference to a class that was deleted? Hoping that it was just a update missed in the PR

https://github.com/killrweather/killrweather/blob/version_upgrade/killrweather-app/src/it/scala/com/datastax/killrweather/KafkaStreamingActorSpec.scala#L47

**Pull request merged**
